include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    
    # Código Limpo
    prefer_single_quotes: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: false
    
    # Segurança
    cancel_subscriptions: true
    close_sinks: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/**"
