include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance (CRITICAL for optimization)
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true
    
    # Memory & Resources
    cancel_subscriptions: true
    close_sinks: true
    
    # Clean Code
    prefer_single_quotes: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_late: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    
    # Production (NO debug prints)
    avoid_print: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    avoid_print: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/**"
