# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance - Crítico para otimização
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    
    # Código Limpo
    prefer_single_quotes: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Evitar debug prints em produção
    # avoid_print: true  # Descomentado para produção
    
    # Segurança e melhores práticas
    cancel_subscriptions: true
    close_sinks: true
    
    # Documentação (opcional para bibliotecas)
    # public_member_api_docs: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/l10n/**"
